### PR TITLE
Full Oculus Quest Inputs

### PR DESCRIPTION
**Pull request by HexaField**
Adds full oculus quest controls including onscreen thumbsticks & all buttons.

### CODE REVIEW

**Comment by takahirox** [comment]
Thanks for the PR! Give me some more time to review. I'm just back from the medical leave now...

**Comment by HexaField** [comment]
Any update on getting this merged?

**Comment by yuripourre** [comment]
That would be a really nice addition! The code looks good, I will test your branch this weekend.

Thanks, @HexaField

**Comment by homanchou** [comment]
Any update?  I would also love to have the other oculus quest inputs supported.

**Pull request closed without merging**
